# GitHub Pages Jekyll Theme Configuration for Bryce Jensen's Portfolio
title: Bryce Jensen - Broadcaster for Boise State Esports
description: Highlight clips, play-by-play commentary reels, and live stream schedule.
remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme

# Site settings & social links
twitter_username: BryceCasts
github_username: brycejensen14
mwec_team: Boise State Esports
